baseURL = "https://example.com"
title = "A0d3n"  
theme = "m10c"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "A0d3n"
  description = "Hello, my articles are at your disposal. Enjoy"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/a0d3n"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/a0d3n"
  [[params.social]]
    icon = "rootme"
    name = "RootMe"
    url = "https://root-me.com/aoden"
  url = "/about/"

  # Green theme
  [params.style]
    darkestColor = "#242930"
    darkColor = "#353b43"
    lightColor = "#afbac4"
    lightestColor = "#ffffff"
    primaryColor = "#57cc8a"

